### PR TITLE
make yamllint happy

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Pre step to add this repo to the openshift ci
following https://github.com/adrienverge/yamllint
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by sjug** [comment]
Why did we replace `yes` with `true`?

**Comment by ArangoGutierrez** [comment]
> Why did we replace `yes` with `true`?

It appears that Yaml Linters complain about Yes vs True

**Comment by ArangoGutierrez** [comment]
According to Ansible documentation both statements are valid

**Comment by sjug** [comment]
@ArangoGutierrez I mean of course they're valid, that's why we're using `yes`.

**Comment by ArangoGutierrez** [comment]
To enable `yes` passing the lint check, we can append this line to the `.yamllint.conf` -> `  truthy: disable` if you feel very strong about `yes`  vs `true` I am happy to append this line

**Comment by sjug** [comment]
I don't like it but I guess we'll change it.

**Review by sjug — APPROVED** [review]

**Pull request merged**
